services:
    mazeltof.vectoricons.listener:
        class: mazeltof\vectoricons\event\listener
        arguments:
        - @template
        - @user
        - %core.root_path%
        tags:
            - { name: event.listener }